### ISSUE TITLE
Mass upgrade operation status is always "In progress"

### ISSUE THREAD

**Issue by sergorl** [openwisp/openwisp-firmware-upgrader#202] opened 2022-07-13 17:06 UTC
Mass upgrade operation status is always [In progress](https://ibb.co/ryyMCK3). But firmware upgrading for one single device works OK.

How to fix it? Please, help )

**Comment by sergorl** [comment] 2022-07-14 15:01
Here is the log:

```bash
==> /opt/openwisp2/log/celery-firmware-upgrader.log <==
[2022-07-14 14:50:16,409: INFO/MainProcess] Task openwisp_firmware_upgrader.tasks.batch_upgrade_operation[e44a19e4-a132-402f-bcbd-2deca7a63ae5] received

==> /opt/openwisp2/log/nginx.access.log <==
10.252.1.8 - - [14/Jul/2022:14:50:16 +0000] "POST /admin/firmware_upgrader/build/ HTTP/1.1" 302 0 "https://openwisp.internal.chirpwireless.io/admin/firmware_upgrader/build/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"

==> /opt/openwisp2/log/uwsgi.log <==
[pid: 21966|app: 0|req: 8494/8494] 10.252.1.8 () {70 vars in 1572 bytes} [Thu Jul 14 14:50:16 2022] POST /admin/firmware_upgrader/build/ => generated 0 bytes in 25 msecs (HTTP/1.1 302) 11 headers in 712 bytes (1 switches on core 0)

==> /opt/openwisp2/log/celery-firmware-upgrader.log <==
[2022-07-14 14:50:16,431: ERROR/ForkPoolWorker-1] Task openwisp_firmware_upgrader.tasks.batch_upgrade_operation[e44a19e4-a132-402f-bcbd-2deca7a63ae5] raised unexpected: ValidationError({'all': ['Device model and image model do not match']})
Traceback (most recent call last):
File "/opt/openwisp2/env/lib/python3.8/site-packages/celery/app/trace.py", line 451, in trace_task
R = retval = fun(args, **kwargs)
File "/opt/openwisp2/env/lib/python3.8/site-packages/celery/app/trace.py", line 734, in protected_call
return self.run(args, **kwargs)
File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_firmware_upgrader/tasks.py", line 51, in batch_upgrade_operation
batch_operation.upgrade(firmwareless=firmwareless)
File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_firmware_upgrader/base/models.py", line 407, in upgrade
self.upgrade_related_devices()
File "/opt/openwisp2/env/lib/python3.8/site-packages/openwisp_firmware_upgrader/base/models.py", line 432, in upgrade_related_devices
device_fw.full_clean()
File "/opt/openwisp2/env/lib/python3.8/site-packages/django/db/models/base.py", line 1405, in full_clean
raise ValidationError(errors)
django.core.exceptions.ValidationError: {'all': ['Device model and image model do not match']}
```

`Device model and image model do not match` but type of Firmware Image is `Miromico miro Edge 7688` and model of device is also `Miromico miro Edge 7688`.

**Comment by nemesisdesign** [comment] 2022-07-15 19:28
@sergorl `Miromico miro Edge 7688` is not a type of image that is still added to our hardware list here, so it's hard for me to debug what's exactly wrong there, but there's something which is triggering this error and you need to find out on your own or share your configuration.

I doubt this is a bug, it's most likely a misconfiguration on your end.

**Comment by sergorl** [comment] 2022-07-18 07:03
@nemesisdesign . I don't understand how, but after rebootng machine it works...

**Comment by sergorl** [comment] 2022-07-18 07:05
> @sergorl `Miromico miro Edge 7688` is not a type of image that is still added to our hardware list here, so it's hard for me to debug what's exactly wrong there, but there's something which is triggering this error and you need to find out on your own or share your configuration.
> 
> I doubt this is a bug, it's most likely a misconfiguration on your end.

what's exactly I should share for you?

**Comment by nemesisdesign** [comment] 2022-07-21 14:35
Closing because it's not a bug.

> > @sergorl `Miromico miro Edge 7688` is not a type of image that is still added to our hardware list here, so it's hard for me to debug what's exactly wrong there, but there's something which is triggering this error and you need to find out on your own or share your configuration.
> > I doubt this is a bug, it's most likely a misconfiguration on your end.
> 
> what's exactly I should share for you?

The configuration for the `Miromico miro Edge 7688`.

**Closed by nemesisdesign** 2022-07-21 14:35 UTC
